MvcFilme/Controllers/CartazesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MvcFilme.Data;
using MvcFilme.Models;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace MvcFilme.Controllers
{
    public class CartazesController : Controller
    {
        private readonly MvcFilmeContext _context;

        public CartazesController(MvcFilmeContext context)
        {
            _context = context;
        }

        // GET /Cartazes/Details/GUID
        public async Task<IActionResult> Details([FromRoute(Name = "id")] Guid publicId)
        {
            var cartaz = await _context.Cartaz.Include(ca => ca.Filme).Include(ca => ca.Cinema).FirstOrDefaultAsync(ca => ca.PublicId == publicId);

            if (cartaz == null)
                return NotFound();

            return View(cartaz);
        }

        // GET /Cartazes/Create
        public async Task<IActionResult> Create([Bind("FilmePublicId,CinemaPublicId")] CartazViewModel cartazViewModel)
        {
            await cartazViewModel.SetSelectListItems(_context);
            ModelState.Clear();
            return View(cartazViewModel);
        }


        // POST /Cartazes/Create
        [HttpPost, ActionName("Create")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreatePost([Bind("FilmePublicId,CinemaPublicId,InicioExibicao,FimExibicao,Preco")] CartazViewModel cartazViewModel)
        {
            var cartaz = new Cartaz
            {
                InicioExibicao = cartazViewModel.InicioExibicao,
                FimExibicao = cartazViewModel.FimExibicao,
                Preco = cartazViewModel.Preco
            };

            cartaz.FilmeId = await _context.Filme.Where(f => f.PublicId == cartazViewModel.FilmePublicId).Select(f => f.Id).FirstOrDefaultAsync();
            cartaz.CinemaId = await _context.Cinema.Where(c => c.PublicId == cartazViewModel.CinemaPublicId).Select(c => c.Id).FirstOrDefaultAsync();

            if (cartaz.FilmeId == 0)
                ModelState.AddModelError("FilmePublicId", "Filme não existe");

            if (cartaz.CinemaId == 0)
                ModelState.AddModelError("CinemaPublicId", "Cinema não existe");

            if (ModelState.IsValid)
            {
                _context.Add(cartaz);
                await _context.SaveChangesAsync();
                SetMessage("O cartaz foi adicionado com sucesso", "success");
                return RedirectToAction("Details", "Cinemas", new { id = cartazViewModel.CinemaPublicId });
            }

            await cartazViewModel.SetSelectListItems(_context);
            return View(cartazViewModel);
        }

        // GET /Cartazes/Edit/GUID
        public async Task<IActionResult> Edit([FromRoute(Name = "id")] Guid? publicId)
        {
            if (publicId == null)
                return PublicIdRequired();

            var cartaz = await _context.Cartaz.Include(ca => ca.Filme).Include(ca => ca.Cinema).FirstOrDefaultAsync(ca => ca.PublicId == publicId);

            if (cartaz == null)
                return CartazNotFound();

            var cartazViewModel = new CartazViewModel
            {
                Cartaz = cartaz,
                InicioExibicao = cartaz.InicioExibicao,
                FimExibicao = cartaz.FimExibicao,
                Preco = cartaz.Preco,
                FilmePublicId = cartaz.Filme.PublicId,
                CinemaPublicId = cartaz.Cinema.PublicId
            };

            await cartazViewModel.SetSelectListItems(_context);

            return View(cartazViewModel);
        }

        // POST /Cartazes/Edit/GUID
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([FromRoute(Name = "id")] Guid? publicId, [Bind("FilmePublicId,CinemaPublicId,InicioExibicao,FimExibicao,Preco")] CartazViewModel cartazViewModel)
        {
            if (publicId == null)
                return PublicIdRequired();

            var cartaz = await _context.Cartaz.FirstOrDefaultAsync(ca => ca.PublicId == publicId);

            if (cartaz == null)
                return CartazNotFound();

            cartaz.InicioExibicao = cartazViewModel.InicioExibicao;
            cartaz.FimExibicao = cartazViewModel.FimExibicao;
            cartaz.Preco = cartazViewModel.Preco;
            cartaz.FilmeId = await _context.Filme.Where(f => f.PublicId == cartazViewModel.FilmePublicId).Select(f => f.Id).FirstOrDefaultAsync();
            cartaz.CinemaId = await _context.Cinema.Where(c => c.PublicId == cartazViewModel.CinemaPublicId).Select(c => c.Id).FirstOrDefaultAsync();

            if (cartaz.FilmeId == 0)
                ModelState.AddModelError("FilmePublicId", "Filme não existe");

            if (cartaz.CinemaId == 0)
                ModelState.AddModelError("CinemaPublicId", "Cinema não existe");

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(cartaz);
                    await _context.SaveChangesAsync();
                    SetMessage("Cartaz atualizado com sucesso", "success");
                    return RedirectToAction("Details", "Cinemas", new { id = cartazViewModel.CinemaPublicId });
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CartazExists(cartaz.Id))
                        return CartazNotFound();
                    else
                        throw;
                }
            }

            await cartazViewModel.SetSelectListItems(_context);
            return View(cartazViewModel);
        }

        public bool CartazExists(int id) =>
            _context.Cartaz.Any(ca => ca.Id == id);

        // GET /Cartazes/Delete/GUID
        public async Task<IActionResult> Delete([FromRoute(Name = "id")] Guid? publicId)
        {
            if (publicId == null)
                return PublicIdRequired();

            var cartaz = await _context.Cartaz.Include(ca => ca.Filme).Include(ca => ca.Cinema).FirstOrDefaultAsync(ca => ca.PublicId == publicId);

            if (cartaz == null)
                return CartazNotFound();

            return View(cartaz);
        }

        // POST /Cartazes/Delete/GUID
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ConfirmDelete(Guid publicId)
        {
            var cartaz = await _context.Cartaz.Include(ca => ca.Cinema).FirstOrDefaultAsync(ca => ca.PublicId == publicId);

            if (cartaz == null)
                return CartazNotFound();


            _context.Remove(cartaz);
            await _context.SaveChangesAsync();
            SetMessage("Cartaz removido com sucesso", "success");
            await CinemasViewModel.UpdateCidades(_context);
            return RedirectToAction("Details", "Cinemas", new { id = cartaz.Cinema.PublicId });
        }

        private void SetMessage(string message, string type)
        {
            TempData["Message"] = message;
            TempData["MessageType"] = type;
        }

        private IActionResult PublicIdRequired()
        {
            SetMessage("Um id deve ser passado", "danger");
            return RedirectToActionPermanent(nameof(Create));
        }

        private IActionResult CartazNotFound()
        {
            SetMessage("Cartaz não existe", "danger");
            return RedirectToActionPermanent(nameof(Create));
        }
    }
}

MvcFilme/Controllers/FilmesController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MvcFilme.Data;
using MvcFilme.Models;
using MvcFilme.Utils;
using Microsoft.EntityFrameworkCore;

namespace MvcFilme.Controllers
{
    public class FilmesController : Controller
    {
        private readonly MvcFilmeContext _context;

        public FilmesController(MvcFilmeContext context)
        {
            _context = context;
        }

        // GET: Filmes
        public async Task<IActionResult> Index([Bind("Genero,Classificacao,BuscaTitulo,AnoLancamento,Ordem,OrdenaPor,PaginaAtual,QuantidadeDeItemPorPagina")] FilmesViewModel filmesViewModel)
        {
            var query = from f in _context.Filme select f;

            if (!String.IsNullOrEmpty(filmesViewModel.BuscaTitulo))
                query = query .Where(f => f.Titulo.Contains(filmesViewModel.BuscaTitulo));
            if(filmesViewModel.Genero != null)
                query = query .Where(f => f.Genero.Equals(filmesViewModel.Genero));
            if(filmesViewModel.Classificacao != null)
                query = query.Where(f => f.Classificacao.Equals(filmesViewModel.Classificacao));
            if (filmesViewModel.AnoLancamento != 0)
                query = query.Where(f => f.Lancamento.Year == filmesViewModel.AnoLancamento);

            switch(filmesViewModel.OrdenaPor)
            {
                case "insercao":
                    if (filmesViewModel.Ordem)
                        query = query.OrderByDescending(f => f.Inserted);
                    else
                        query = query.OrderBy(f => f.Inserted);
                    break;
                case "titulo":
                    if (filmesViewModel.Ordem)
                        query = query.OrderByDescending(f => f.Titulo);
                    else
                        query = query.OrderBy(f => f.Titulo);
                    break;
                case "lancamento":
                    if (filmesViewModel.Ordem)
                        query = query.OrderByDescending(f => f.Lancamento);
                    else
                        query = query.OrderBy(f => f.Lancamento);
                    break;
            }


            await filmesViewModel.SetSelectListItems(_context);
            filmesViewModel.Filmes = await PaginatedList<Filme>.CreateAsync(query, filmesViewModel.PaginaAtual, filmesViewModel.QuantidadeDeItemPorPagina);
            return View(filmesViewModel);
        }

        // GET: Filmes/Details/GUID
        public async Task<IActionResult> Details([FromRoute(Name = "id")]Guid? publicId, [Bind("ApenasEmCartaz,CinemaNome,CinemaCidade,CinemaEstado,InicioExibicao,FimExibicao")] FilmeViewModel filmeViewModel)
        {
            if (publicId == null)
                return PublicIdRequired();

            var filme = await _context.Filme.FirstOrDefaultAsync(m => m.PublicId == publicId);

            if (filme == null)
                return FilmeNotFound();
            

            var hoje = DateTime.Now;

            filmeViewModel.Filme = filme;
            var query = _context.Cartaz.Where(ca => ca.Filme.Id == filme.Id);

            if (filmeViewModel.ApenasEmCartaz)
                query = query.Where(ca =>  ca.FimExibicao >= hoje);

            if (filmeViewModel.InicioExibicao != null)
                query = query.Where(ca => ca.InicioExibicao >= filmeViewModel.InicioExibicao);

            if (filmeViewModel.FimExibicao != null)
                query = query.Where(ca => ca.FimExibicao <= filmeViewModel.FimExibicao);

            if (!String.IsNullOrWhiteSpace(filmeViewModel.CinemaNome))
                query = query.Where(ca => ca.Cinema.Nome == filmeViewModel.CinemaNome);

            if (!String.IsNullOrWhiteSpace(filmeViewModel.CinemaCidade))
                query = query.Where(ca => ca.Cinema.Cidade == filmeViewModel.CinemaCidade);

            if (filmeViewModel.CinemaEstado != null)
                query = query.Where(ca => ca.Cinema.UnidadeFederativa == filmeViewModel.CinemaEstado);

            filmeViewModel.Cartazes = await query.Include(ca => ca.Cinema).ToListAsync();

            await filmeViewModel.SetSelectListItems(_context);

            return View(filmeViewModel);
        }

        // GET: Filmes/Create
        public IActionResult Create() => View();
       

        // POST: Filmes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Titulo,Lancamento,Genero,Capa,Classificacao,Sinopse")] Filme filme)
        {
            if (ModelState.IsValid)
            {
                _context.Add(filme);
                await _context.SaveChangesAsync();
                SetMessage(filme.Titulo + " foi criado com sucesso!", "success");
                return RedirectToAction(nameof(Index));
            }
            return View(filme);
        }

        // GET: Filmes/Edit/GUID
        public async Task<IActionResult> Edit([FromRoute(Name = "id")]Guid? publicId)
        {
            if (publicId == null)
                return PublicIdRequired();
            

            var filme = await _context.Filme.FirstOrDefaultAsync(f => f.PublicId == publicId);
            if (filme == null)
                return FilmeNotFound();
            
            return View(filme);
        }

        // POST: Filmes/Edit/GUID
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([FromRoute(Name = "id")]Guid? publicId, [Bind("PublicId,Titulo,Lancamento,Genero,Capa,Classificacao,Sinopse")] Filme updatedFilme)
        {
            if (publicId == null)
                return PublicIdRequired(); 

            var filme = await _context.Filme.AsNoTracking().Where(f => f.PublicId.Equals(publicId)).Select(f => f).FirstOrDefaultAsync();

            if (filme == null)
                return FilmeNotFound();

            updatedFilme.Id = filme.Id;
            updatedFilme.Inserted = filme.Inserted;
            updatedFilme.LastUpdated = filme.LastUpdated;
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Filme.Update(updatedFilme);
                    SetMessage(updatedFilme.Titulo + " foi atualizado criado com sucesso!", "success");
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FilmeExists(filme.Id))
                    {
                        SetMessage("Filme não existe", "danger");
                        return RedirectToAction(nameof(Index));
                    }
                    else
                        throw;
                }
                return RedirectToAction(nameof(Details), new {Id = updatedFilme.PublicId});
            }
            return View(updatedFilme);
        }

        // GET: Filmes/Delete/GUID
        public async Task<IActionResult> Delete([FromRoute(Name = "id")]Guid? publicId)
        {
            if (publicId == null)
                return PublicIdRequired(); 

            var filme = await _context.Filme
                .FirstOrDefaultAsync(m => m.PublicId.Equals(publicId));

            if (filme == null)
                return FilmeNotFound();

            return View(filme);
        }

        // POST: Filmes/Delete/GUID
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid publicId)
        {
            var filme = await _context.Filme.FirstOrDefaultAsync(f => f.PublicId.Equals(publicId));

            if (filme == null)
            {
                return NotFound();
            }

            if(filme.Cartazes.Count > 0)
            {
                SetMessage("Não é possível remover um filme que está em algum cartaz", "warning");
                return RedirectToAction("Details", "Filmes", new {id = filme.PublicId}, "cartazes");
            }    

            _context.Filme.Remove(filme);
            await _context.SaveChangesAsync();
            SetMessage(filme.Titulo + " foi removido com successo", "success");
            return RedirectToAction(nameof(Index));
        }

        private bool FilmeExists(int id) =>
            _context.Filme.Any(e => e.Id == id);

        private void SetMessage(string message, string type)
        {
            TempData["Message"] = message;
            TempData["MessageType"] = type;
        }
        private IActionResult PublicIdRequired()
        {
            SetMessage("Um id deve ser passado", "danger");
            return RedirectToActionPermanent(nameof(Index));
        }
        private IActionResult FilmeNotFound()
        {
            SetMessage("Filme não existe", "danger");
            return RedirectToActionPermanent(nameof(Index));
        }
    }
}

MvcFilme/Views/Filmes/Create.cshtml
@model Filme

@{
    ViewData["Title"] = "Novo Filme";
}

<div class="container novo-filme bg-light pt-4 pb-5 ">
    <div class="row mb-4 px-5">
        <div class="col">
            <a asp-action="Index" class="link-secondary p-2">Voltar para o Catálogo</a>
        </div>
    </div>
    <div class="row d-flex justify-content-center">
        <div class="col-md-4 border p-3 border-success rounded">
            <h2 class="text-center">Novo Filme</h2>
            <form asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <hr />
                <div class="mb-3">
                    <label asp-for="Titulo" class="form-label"></label>
                    <input asp-for="Titulo" class="form-control" placeholder="Interestelar" />
                    <span asp-validation-for="Titulo" class="text-danger invalid-msg"></span>
                </div>
                <div class="mb-3">
                    <label asp-for="Lancamento" class="form-label"></label>
                    <input asp-for="Lancamento" class="form-control" />
                    <span asp-validation-for="Lancamento" class="text-danger invalid-msg"></span>
                </div>
                <div class="mb-3">
                    <label asp-for="Capa" class="form-label"></label>
                    <input asp-for="Capa" class="form-control" placeholder="https://example.com" type="url" />
                    <span asp-validation-for="Capa" class="text-danger invalid-msg"></span>
                </div>
                <div class="mb-3">
                    <label asp-for="Genero" class="form-label"></label>
                    <select asp-for="Genero" asp-items="FilmesViewModel.Generos" class="form-select">
                    </select>
                    <span asp-validation-for="Genero" class="text-danger invalid-msg"></span>
                </div>
                <div class="mb-3">
                    <label asp-for="Classificacao" class="form-label"></label>
                    <select asp-for="Classificacao" asp-items="FilmesViewModel.Classificacoes" class="form-select">
                    </select>
                    <span asp-validation-for="Classificacao" class="text-danger invalid-msg"></span>
                </div>
                <div class="mb-3">
                    <label asp-for="Sinopse" class="form-label"></label>
                    <textarea class="form-control" asp-for="Sinopse" rows="3"></textarea>
                    <span asp-validation-for="Sinopse"></span>
                </div>
                <div class="d-flex px-5">
                    <input type="submit" value="Salvar" class="btn btn-success w-100 h-100" />
                </div>
            </form>
        </div>
    </div>
</div>



@section Scripts {
    @{
    await Html.RenderPartialAsync("_ValidationScriptsPartial");
}
}

MvcFilme/Views/Filmes/Delete.cshtml
@model Filme

@{
    ViewData["Title"] = "Deseja remover " + Model.Titulo + "?";
}
<div class="container bg-light p-5 remover-filme">
    <h2 class="text-center">Você relamente deseja apagar @Html.DisplayFor(model => model.Titulo)?</h2>
    <div class="row d-flex justify-content-center">

        <div class="col-5 bg-white border mt-4 border-danger p-3 rounded">
            <div class="row d-flex justify-content-center align-items-center">
                <img src="@Model.Capa" class="filme-capa rounded" alt="" />
            </div>
            <div class="row pt-3">
                <dl>
                    <dt>@Html.DisplayNameFor(model => model.Titulo)</dt>
                    <dd>@Html.DisplayFor(model => model.Titulo)</dd>
                </dl>
                <dl>
                    <dt>@Html.DisplayNameFor(model => model.Genero)</dt>
                    <dd>@Html.DisplayFor(model => model.Genero)</dd>
                </dl>
                <dl>
                    <dt>@Html.DisplayNameFor(model => model.Classificacao)</dt>
                    <dd>@Html.DisplayFor(model => model.Classificacao)</dd>
                </dl>
                <dl>
                    <dt>@Html.DisplayNameFor(model => model.Lancamento)</dt>
                    <dd>@Html.DisplayFor(model => model.Lancamento)</dd>
                </dl>
                <dl>
                    <dt>@Html.DisplayNameFor(model => model.Sinopse)</dt>
                    <dd class="text-justify text-indented">
                        @Html.DisplayFor(model => model.Sinopse)
                    </dd>
                </dl>
            </div>
            <div class="row">
                <div class="col">
                    <a class="btn btn-secondary mb-2 w-100" asp-action="Index">Catálogo</a>
                </div>
                <div class="col">
                    <form asp-action="Delete" class="w-100 p-0">
                        <input type="hidden" asp-for="PublicId"/>
                        <input type="submit" class="btn btn-danger w-100" value="Confirmar" />
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

MvcFilme/Views/Filmes/Details.cshtml
@model FilmeViewModel

@{
    ViewData["Title"] = Model.Filme.Titulo;
}

<div class="container bg-light p-4 detalhes-filme">
    <h3 class="text-center">Detalhes - @Html.DisplayFor(model => model.Filme.Titulo)</h3>
    <div class="row bg-white border mt-4 border-warning p-2 rounded">
            <div class="col-auto d-flex justify-content-end align-items-center">
                <img src="@Model.Filme.Capa" class="filme-capa rounded" alt="" />
            </div>
            <div class="col pt-3">
                <dl>
                    <dt>@Html.DisplayNameFor(model => model.Filme.Titulo)</dt>
                    <dd>@Html.DisplayFor(model => model.Filme.Titulo)</dd>
                </dl>
                <dl>
                    <dt>@Html.DisplayNameFor(model => model.Filme.Genero)</dt>
                    <dd>@Html.DisplayFor(model => model.Filme.Genero)</dd>
                </dl>
                <dl>
                    <dt>@Html.DisplayNameFor(model => model.Filme.Classificacao)</dt>
                    <dd>@Html.DisplayFor(model => model.Filme.Classificacao)</dd>
                </dl>
                <dl>
                    <dt>@Html.DisplayNameFor(model => model.Filme.Lancamento)</dt>
                    <dd>@Html.DisplayFor(model => model.Filme.Lancamento)</dd>
                </dl>
                <dl>
                    <dt>@Html.DisplayNameFor(model => model.Filme.Sinopse)</dt>
                    <dd class="text-justify text-indented">
                        @Html.DisplayFor(model => model.Filme.Sinopse)
                    </dd>
                </dl>
            </div>
            <div class="col-2 d-flex flex-column justify-content-between">
                    <a class="btn btn-secondary w-100" asp-action="Index">Catálogo</a>
                    <a class="btn btn-primary w-100" asp-action="Edit" asp-route-id="@Model.Filme.PublicId">Editar</a>
                    <a class="btn btn-danger w-100" asp-action="Delete" asp-route-id="@Model.Filme.PublicId">Remover</a>
            </div>
    </div>
    <hr />
    <div class="container-fluid" id="cartazes">
        <h3 class="text-center">Cartazes</h3>
        <div class="row mt-4">
            <div class="col-10 border rounded p-2">
                <h5 class="text-center">Filtros</h5>
                <form class="container justify-content-around" asp-fragment="cartazes"  method="get">
                    <div class="row justify-content-around">
                        <div class="col">
                            <label asp-for="ApenasEmCartaz" class="form-label"></label>
                            <div class="w-100 d-flex justify-content-center pt-2">
                                <input class="form-check-input" asp-for="ApenasEmCartaz" type="checkbox"/>
                            </div>
                        </div>
                        <div class="col">
                            <label class="form-label" asp-for="CinemaNome"></label>
                            <select class="form-select" asp-for="CinemaNome" asp-items="Model.CinemaNomes">
                                <option value="">Todas</option>
                            </select>
                        </div>
                        <div class="col">
                            <label class="form-label" asp-for="CinemaCidade"></label>
                            <select class="form-select" asp-for="CinemaCidade" asp-items="Model.CinemaCidades">
                                <option value="">Todas</option>
                            </select>
                        </div>
                        <div class="col">
                            <label class="form-label" asp-for="InicioExibicao"></label>
                            <input class="form-control" asp-for="InicioExibicao" />
                        </div>
                        <div class="col">
                            <label class="form-label" asp-for="FimExibicao"></label>
                            <input class="form-control" asp-for="FimExibicao" />
                        </div>
                    </div>
                    <div class="row pt-2 d-flex justify-content-center">
                        <input class="btn btn-outline-primary w-50" type="submit" value="Filtrar" />
                    </div>
                </form>
            </div>
            <div class="col-2 p-3 d-flex justify-content-center align-items-center">
                <a asp-controller="Cartazes" asp-action="Create" asp-route-FilmePublicId="@Model.Filme.PublicId" class="btn btn-success w-100">Novo Cartaz</a>
            </div>
        </div>
        <div class="col-2">
        </div>
        <div class="row mt-2 border bg-light rounded px-4 py-2 justify-content-center">
            <table class="table table-striped w-100">
                <thead>
                    <tr>
                        <th scope="col">
                            #
                        </th>
                        <th scope="col">
                             @Html.DisplayNameFor(m => m.CinemaNome)
                        </th>
                        <th scope="col">
                             @Html.DisplayNameFor(m => m.CinemaCidade)
                        </th>
                        <th scope="col">
                             @Html.DisplayNameFor(m => m.CinemaEstado)
                        </th>
                        <th scope="col">
                             @Html.DisplayNameFor(m => m.Cartazes.FirstOrDefault().InicioExibicao)
                        </th>
                        <th scope="col">
                             @Html.DisplayNameFor(m => m.Cartazes.FirstOrDefault().FimExibicao)
                        </th>
                        <th scope="col">
                             @Html.DisplayNameFor(m => m.Cartazes.FirstOrDefault().Preco)
                        </th>
                        <th scope="col">
                            Ações
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @for(int i = 0; i < Model.Cartazes.Count; i++)
                    {
                        <tr>
                            <th scope="row">
                                @(i+1)
                            </th>
                            <td>
                                <a class="link-secondary" asp-controller="Cinemas" asp-action="Details" asp-route-id="@Model.Cartazes[i].Cinema.PublicId" >@Html.DisplayFor(_ => Model.Cartazes[i].Cinema.Nome)</a> 
                            </td>
                            <td>
                                @Html.DisplayFor(_ => Model.Cartazes[i].Cinema.Cidade)
                            </td>
                            <td>
                                @Html.DisplayFor(_ => Model.Cartazes[i].Cinema.UnidadeFederativa)
                            </td>
                            <td>
                                @Html.DisplayFor(_ => Model.Cartazes[i].InicioExibicao)
                            </td>
                            <td>
                                @Html.DisplayFor(_ => Model.Cartazes[i].FimExibicao)
                            </td>
                            <td>
                                @Html.DisplayFor(_ => Model.Cartazes[i].Preco)
                            </td>
                            <td>
                                <div class="container-fluid">
                                    <div class="row justify-content-around">
                                        <div class="col text-center">
                                            <a  asp-controller="Cartazes" asp-action="Details" class="link-warning w-100" asp-route-id="@Model.Cartazes[i].PublicId">Detalhes</a>
                                        </div>
                                        <div class="col text-center">
                                            <a  asp-controller="Cartazes" asp-action="Edit" class="link-primary w-100" asp-route-id="@Model.Cartazes[i].PublicId">Editar</a>
                                        </div>
                                        <div class="col text-center">
                                            <a  asp-controller="Cartazes" asp-action="Delete" class="link-danger w-100" asp-route-id="@Model.Cartazes[i].PublicId">Remover</a>
                                        </div>
                                    </div>
                                </div>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>